name: m3e_haptics
description: High-fidelity AOSP-aligned native haptic feedback compositions for Flutter.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  plugin:
    platforms:
      android:
        package: com.android.m3e_haptics
        pluginClass: M3eHapticsPlugin
